name: Python CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Installing Poetry
      uses: snok/install-poetry@v1
      with:
        version: "1.1.12"
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Cache Poetry dependencies
      uses: actions/cache@v2
      with:
          path: .venv
          key: pydeps-${{ hashFiles('**/poetry.lock') }}
    
    
    - name: Install dependencies
      run: |
        cd backend
        poetry install --no-interaction
    
    - name: Run Tests
      run: |
        pytest backend/tests.py  
